/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorafinanciera;

/**
 *
 * @author jhon
 */
public class VentanaAnualidades extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAnualidades
     */
    public VentanaAnualidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textVA = new javax.swing.JTextField();
        btnInteres = new javax.swing.JButton();
        textI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textNper = new javax.swing.JTextField();
        textResultado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rbtnEfectiva = new javax.swing.JRadioButton();
        textVF = new javax.swing.JTextField();
        rbtnNominal = new javax.swing.JRadioButton();
        btnRegresar = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNper2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboxCalculo = new javax.swing.JComboBox<>();
        txtI2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtPagos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textVA.setEnabled(false);

        btnInteres.setText("Tasa Equvalente");
        btnInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteresActionPerformed(evt);
            }
        });

        textI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIActionPerformed(evt);
            }
        });

        jLabel4.setText("Periodo (n):");

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        textNper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNperActionPerformed(evt);
            }
        });

        textResultado.setEditable(false);

        jLabel5.setText("Tasa de Interes (i):");

        jLabel6.setText("Valor Futuro (VF):");

        rbtnEfectiva.setText("Tasa Efectiva");
        rbtnEfectiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEfectivaActionPerformed(evt);
            }
        });

        rbtnNominal.setText("Tasa Nominal");
        rbtnNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNominalActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel7.setText("Periodo de Capitalizacion (m):");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("Anualidades");

        jLabel2.setText("Elija una opcion de calculo:");

        jLabel8.setText("Tasa Nominal (j):");

        comboxCalculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VA", "VF", "n con VA", "n con VF", "i con VA", "i Con VF", "Pagos con VA", "Pagos con VF", " " }));
        comboxCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxCalculoActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor Actual (VA):");

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Pagos:");

        jButton3.setText("Tabla de Amortizacion");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtnEfectiva)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(254, 254, 254))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textVF, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(txtPagos, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(comboxCalculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel5)
                                                                .addComponent(textI, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(textNper, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(18, 18, 18)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel8)
                                                                .addComponent(txtI2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                                                .addComponent(txtNper2)))
                                                        .addComponent(textVA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(116, 116, 116)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(btnInteres)
                                    .addComponent(jButton3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(rbtnNominal)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnEfectiva)
                    .addComponent(rbtnNominal))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(comboxCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(textResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNper2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInteres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnRegresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textVF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteresActionPerformed
        VentanaTasa tasa = new VentanaTasa();
        tasa.setVisible(true);
    }//GEN-LAST:event_btnInteresActionPerformed

    private void textIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(this.comboxCalculo.getSelectedIndex()){
            case 0:
                double va = 0;
                if(this.rbtnEfectiva.isSelected()){
                    va = Double.parseDouble(this.txtPagos.getText())*((1-Math.pow(1+Double.parseDouble(this.textI.getText()), -Double.parseDouble(this.textNper.getText())))/Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    va = Double.parseDouble(this.txtPagos.getText())*((1-Math.pow(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())), -Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",va));
                break;
            case 1:
                double vf = 0;
                if(this.rbtnEfectiva.isSelected()){
                    vf = Double.parseDouble(this.txtPagos.getText())*((-1+Math.pow(1+Double.parseDouble(this.textI.getText()), Double.parseDouble(this.textNper.getText())))/Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    vf = Double.parseDouble(this.txtPagos.getText())*((-1+Math.pow(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())), Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",vf));
                break;
            case 2:
                double nper = 0;
                if(this.rbtnEfectiva.isSelected()){
                    nper = -(Math.log(1-((Double.parseDouble(this.textVA.getText())*Double.parseDouble(this.textI.getText()))/Double.parseDouble(this.txtPagos.getText()))))/Math.log(1+Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    nper = -(Math.log(1-((Double.parseDouble(this.textVA.getText())*Double.parseDouble(this.txtI2.getText()))/(Double.parseDouble(this.txtPagos.getText())*Double.parseDouble(this.txtNper2.getText())))))/Math.log(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",nper));
                break;
            case 3:
            double nper2 = 0;
                if(this.rbtnEfectiva.isSelected()){
                    nper2 = (Math.log(1+((Double.parseDouble(this.textVF.getText())*Double.parseDouble(this.textI.getText()))/Double.parseDouble(this.txtPagos.getText()))))/Math.log(1+Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    nper2 = (Math.log(1+((Double.parseDouble(this.textVF.getText())*Double.parseDouble(this.txtI2.getText()))/(Double.parseDouble(this.txtPagos.getText())*Double.parseDouble(this.txtNper2.getText())))))/Math.log(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",nper2));
                break;
            case 4:
                double i = 0;
                boolean salir = true;
                double vaV= Double.parseDouble(this.textVA.getText());
                double vaP = 0;
                if(this.rbtnEfectiva.isSelected()){
                    while(salir){
                        vaP = Double.parseDouble(this.txtPagos.getText())*((1-Math.pow(1+i, -Double.parseDouble(this.textNper.getText())))/i);
                        if((vaV-0.005)<vaP && vaP<(vaV+0.005)){
                            salir = false;
                            this.textResultado.setText(String.format("%.2f",i));
                        }else{
                            i = i+0.001;
                        }
                    }
                }
                if(this.rbtnNominal.isSelected()){
                    while(salir){
                        vaP = Double.parseDouble(this.txtPagos.getText())*((1-Math.pow(1+(i/Double.parseDouble(this.txtNper2.getText())), -Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(i/Double.parseDouble(this.txtNper2.getText())));
                        if((vaV-0.005)<vaP && vaP<(vaV+0.005)){
                            salir = false;
                            this.textResultado.setText(String.format("%.2f",i));
                        }else{
                            i = i+0.001;
                        }
                    }
                }                
                break;
            case 5:
                double i2 = 0;
                boolean salir2 = true;
                double vfV= Double.parseDouble(this.textVF.getText());
                double vfP = 0;
                if(this.rbtnEfectiva.isSelected()){
                    while(salir2){
                        vfP = Double.parseDouble(this.txtPagos.getText())*((-1+Math.pow(1+i2, Double.parseDouble(this.textNper.getText())))/i2);
                        if((vfV-0.005)<vfP && vfP<(vfV+0.005)){
                            salir2 = false;
                            this.textResultado.setText(String.format("%.2f",i2));
                        }else{
                            i2 = i2+0.001;
                        }
                    }
                }
                if(this.rbtnNominal.isSelected()){
                    while(salir2){
                        vfP = Double.parseDouble(this.txtPagos.getText())*((-1+Math.pow(1+(i2/Double.parseDouble(this.txtNper2.getText())), Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(i2/Double.parseDouble(this.txtNper2.getText())));
                        System.out.println(vfP+"    "+i2);
                        if((vfV-0.005)<vfP && vfP<(vfV+0.005)){
                            salir2 = false;
                            this.textResultado.setText(String.format("%.2f",i2));
                        }else{
                            i2 = i2+0.001;
                        }
                    }
                }
                break;
            case 6:
                double p = 0;
                if(this.rbtnEfectiva.isSelected()){
                    p = Double.parseDouble(this.textVA.getText())/((1-Math.pow(1+Double.parseDouble(this.textI.getText()), -Double.parseDouble(this.textNper.getText())))/Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    p = Double.parseDouble(this.textVA.getText())/((1-Math.pow(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())), -Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",p));
                break;
            case 7:
                double p2 = 0;
                if(this.rbtnEfectiva.isSelected()){
                    p2 = Double.parseDouble(this.textVF.getText())/((-1+Math.pow(1+Double.parseDouble(this.textI.getText()), Double.parseDouble(this.textNper.getText())))/Double.parseDouble(this.textI.getText()));
                }
                if(this.rbtnNominal.isSelected()){
                    p2 = Double.parseDouble(this.textVF.getText())/((-1+Math.pow(1+(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())), Double.parseDouble(this.textNper.getText())*Double.parseDouble(this.txtNper2.getText())))/(Double.parseDouble(this.txtI2.getText())/Double.parseDouble(this.txtNper2.getText())));
                }
                this.textResultado.setText(String.format("%.2f",p2));
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textNperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNperActionPerformed

    private void rbtnEfectivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEfectivaActionPerformed
        this.rbtnNominal.setSelected(false);
    }//GEN-LAST:event_rbtnEfectivaActionPerformed

    private void rbtnNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNominalActionPerformed
        this.rbtnEfectiva.setSelected(false);
    }//GEN-LAST:event_rbtnNominalActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VentanaPrincipal vPrincipal = new VentanaPrincipal();
        vPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboxCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxCalculoActionPerformed
        switch(this.comboxCalculo.getSelectedIndex()){
            case 0:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(false);
            this.txtPagos.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(true);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
            }
            break;
            case 1:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(false);
            this.txtPagos.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(true);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(true);
            }
            break;
            case 2:
            this.textVF.setEnabled(false);
            this.textVA.setEnabled(true);
            this.txtPagos.setEnabled(true);
            if(this.rbtnEfectiva.isSelected()){
                this.textI.setEnabled(true);
                this.textNper.setEnabled(false);
                this.txtI2.setEnabled(false);
                this.txtNper2.setEnabled(false);
            }
            if(this.rbtnNominal.isSelected()){
                this.txtI2.setEnabled(true);
                this.txtNper2.setEnabled(true);
                this.textI.setEnabled(false);
                this.textNper.setEnabled(false);
            }
            break;
            case 3:
                this.textVF.setEnabled(true);
                this.textVA.setEnabled(false);
                this.txtPagos.setEnabled(true);
                if(this.rbtnEfectiva.isSelected()){
                    this.textI.setEnabled(true);
                    this.textNper.setEnabled(false);
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(false);
                }
                if(this.rbtnNominal.isSelected()){
                    this.txtI2.setEnabled(true);
                    this.txtNper2.setEnabled(true);
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(false);
                }
            break;
            case 4:
                this.textVF.setEnabled(false);
                this.textVA.setEnabled(true);
                this.txtPagos.setEnabled(true);
                if(this.rbtnEfectiva.isSelected()){
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(false);
                }
                if(this.rbtnNominal.isSelected()){
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(true);
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                }
                break;
            case 5:
                this.textVF.setEnabled(true);
                this.textVA.setEnabled(false);
                this.txtPagos.setEnabled(true);
                if(this.rbtnEfectiva.isSelected()){
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(false);
                }
                if(this.rbtnNominal.isSelected()){
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(true);
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                }
                break;
            case 6:
                this.textVF.setEnabled(false);
                this.textVA.setEnabled(true);
                this.txtPagos.setEnabled(false);
                if(this.rbtnEfectiva.isSelected()){
                    this.textI.setEnabled(true);
                    this.textNper.setEnabled(true);
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(false);
                }
                if(this.rbtnNominal.isSelected()){
                    this.txtI2.setEnabled(true);
                    this.txtNper2.setEnabled(true);
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                }
                break;
            case 7:
                this.textVF.setEnabled(true);
                this.textVA.setEnabled(false);
                this.txtPagos.setEnabled(false);
                if(this.rbtnEfectiva.isSelected()){
                    this.textI.setEnabled(true);
                    this.textNper.setEnabled(true);
                    this.txtI2.setEnabled(false);
                    this.txtNper2.setEnabled(false);
                }
                if(this.rbtnNominal.isSelected()){
                    this.txtI2.setEnabled(true);
                    this.txtNper2.setEnabled(true);
                    this.textI.setEnabled(false);
                    this.textNper.setEnabled(true);
                }
                break;
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxCalculoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.textI.setText("");
        this.textNper.setText("");
        this.textResultado.setText("");
        this.textVA.setText("");
        this.textVF.setText("");
        this.txtI2.setText("");
        this.txtNper2.setText("");
        this.txtPagos.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Amortizacion a = new Amortizacion();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAnualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAnualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAnualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAnualidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAnualidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInteres;
    private javax.swing.JToggleButton btnRegresar;
    private javax.swing.JComboBox<String> comboxCalculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnEfectiva;
    private javax.swing.JRadioButton rbtnNominal;
    private javax.swing.JTextField textI;
    private javax.swing.JTextField textNper;
    private javax.swing.JTextField textResultado;
    private javax.swing.JTextField textVA;
    private javax.swing.JTextField textVF;
    private javax.swing.JTextField txtI2;
    private javax.swing.JTextField txtNper2;
    private javax.swing.JTextField txtPagos;
    // End of variables declaration//GEN-END:variables
}
